export enum Cuadrantes {
  Solicitante = 1,
  GrupoFamiliarSolicitante = 2,
  DestinoFondos = 3,
  CondicionesSolicitadas = 4,
  Cursos = 5,
  Garante = 6,
  DatosEmprendimiento = 7,
  PatrimonioSolicitante = 8,
  OrganizacionEmprendimiento = 9,
  MercadoYComercializacion = 10,
  InversionRealizada = 11,
  DeudaEmprendimiento = 12,
  NecesidadesInversion = 13,
  DescripcionProyecto = 14,
  PrecioVenta = 15,
  ResultadoEconomico = 16,
  IngresosYGastosActuales = 17,
  GrupoFamiliarGarante = 18,
  DetalleGrupoFamiliarSolicitante = 19,
  DetalleGrupoFamiliarGarante = 20,
  Requisitos = 21,
  Integrantes = 22,
  Ong = 23
}
